version: '3.9'

services:

  mongodb:
    image: bitnami/mongodb:latest
    container_name: "nwc-mongodb"
    ports:
      - ${MONGODB_PORT_NUMBER}:${MONGODB_PORT_NUMBER}
    volumes:
      - "mongo_data:/data/db"
    env_file:
      - .env

volumes:
  mongo_data:
